### PR TITLE
target avalonia 0.9.5

### PR DESCRIPTION
**Pull request by danwalmsley**

### CODE REVIEW

**Comment by FoggyFinder** [comment]
not sure I understand why the PR was closed?

**Comment by wieslawsoltes** [comment]
> not sure I understand why the PR was closed?

It's targeting master and master is not mergable for service releases of Avalonia. I have to create release branch based on latest release branch.

https://github.com/wieslawsoltes/AvaloniaBehaviors/tree/release/0.9.5

**Comment by wieslawsoltes** [comment]
@FoggyFinder @danwalmsley 
So in order to update from Avalonia `0.9.4` to `0.9.5` you need to create branch [release/0.9.5](https://github.com/wieslawsoltes/AvaloniaBehaviors/tree/release/0.9.5) from [release/0.9.4](https://github.com/wieslawsoltes/AvaloniaBehaviors/tree/release/0.9.4) and than push necessary changes to `release/0.9.5` branch. The `master` is tracking nightly build and those build have breaking changes so we have to base the service releases on `release/*` branches.

**Comment by wieslawsoltes** [comment]
Also `master` is tracking `0.9.999-cibuild*` nightly builds.

**Pull request closed without merging**
