### PR TITLE
InvokeCommandAction send all parameters

### PR DESCRIPTION
**Pull request by yiszza**

### CODE REVIEW

**Comment by wieslawsoltes** [comment]
This is breaking change and diverges from original UWP version.

**Comment by yiszza** [comment]
> 

i think, this is a good change

**Comment by wieslawsoltes** [comment]
Did you test sample app if it works?

**Comment by wieslawsoltes** [comment]
Why do you need sender object in your view model ?

**Comment by wieslawsoltes** [comment]
Can you post your sample code for which you need this?

**Comment by yiszza** [comment]
for example
`
        public ICommand Img_PointerMovedCommand => new Command((param) =>
        {
            CommandParameters parameters = (CommandParameters)param;
            var eventArgs = (PointerEventArgs)parameters.EventArgs;
            var point = eventArgs.GetPosition((Image)parameters.Sender);

            //sometimes, i need get MousePosition on the Control

        });
`

**Pull request closed without merging**
